### ISSUE TITLE
Setup configurator repo/jenkins for configuring www.m.o

### ISSUE THREAD

**Issue by pmac** [mozmar/infra#263]
We want to use Jenkins to configure our www deployments. @jgmize and I talked and we believe it should work something like the following:

- [x] The `master` branch of this repo should contain all of the configs for the various apps (dev, stage, prod), the Jenkins scripts for applying said configs, and docs for using this system.
- [ ] Pushing changes to `master` should only result in building the docs and pushing them to the `gh-pages` branch of the same repo. The docs should be dynamically updated with the current config state per app.
- [x] To cause config changes to the apps the user would push `master` to an app-specific branch: e.g. `bedrock-prod` or `bedrock-stage`. 
- [ ] There should also be a section of the configs for deleting environment variables that will be triggered by pushing to e.g. `delete/bedrock-stage` or `delete/virginia/bedrock-stage`.
- [x] The `headless` bedrock integration test suite should run against these configuration deployments
- [x] Should be able to run config and test either in parallel or in series depending on the configuration in the YAML files. This will give us the ability to have a branch for parallel runs (e.g. `bedrock-prod-fast`.

Let's continue to discuss this and we can keep this requirements list updated as we go.

**Comment by pmac** [comment]
I'm actually thinking I might take out the requirement for cluster specific pushes. I'm thinking these settings should be consistent, and as long as a test runs between them I'm okay with it rolling out automatically.

**Comment by jgmize** [comment]
> Pushing changes to master should only result in building the docs and pushing them to the gh-pages branch of the same repo. The docs should be dynamically updated with the current config state per app.

I personally prefer publishing from a [docs folder on the master branch](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch), but if using gh-pages makes things easier then I have no objections.

**Comment by pmac** [comment]
publishing from a docs folder would mean generating and checking in the HTML to the master branch and having the docs source somewhere else right? That seems messy.

**Comment by pmac** [comment]
cc @glogiotatidis

**Comment by pmac** [comment]
I converted the list above to a task list. I've got much of it working. It's all in the [new repo](https://github.com/mozmar/www-config).

**Comment by glogiotatidis** [comment]
I like what's happening here and it's in the right direction. A couple implementation ideas and questions:

* Instead of having separate `fast` branches we can add `[fast]` in the commit message of the change we want to go fast. This will allow us one branch per deployment which will prevent configuration mismatch between two branches for the same deployment. Additionally this will allow us to add `milestone` in the pipeline to prevent older configuration to override newer configuration.

*  How do we prevent pipeline (+ helper scripts) diversion among different branches? One solution could be that we have the jenkins and helper scripts in master only and the other branches only have configuration. Jenkins would checkout both to run. Maintaining different contents per branch can be tricky  so maybe a repo with the pipeline, scripts and docs and another with the configuration only files?

* Alternatively to the previous point, what if we only have master branch and on each run Jenkins figures out which instances need updating by diffing between `deis config` and the file in the repo?

**Comment by pmac** [comment]
The way I was thinking about these branches is that they're more actions than storage. The `master` branch should always be the source of truth, and the branches would be pushed to when you wanted to apply the changes. So you could force push a branch like `fast/bedrock-prod` and that would be fine, but `master` should be the up2date one; very much like we do for bedrock and the `prod` branch.

Using commit message is interesting though. We could do a lot with that, but it might be more error prone. We could do specially formatted commit messages (even YAML) that would tell the job exactly which apps to configure and in what mode. We could be doing that for bedrock as well for prod pushes. Hmmmm....

I do have a tool in the repo (`set-config`) that does the pushing of the app branch with the optional `fast/` prefix for you. But it could just as easily format an empty commit and push that.

I'm kinda far along on the branch model, but I do like the commit message suggestion. Maybe we should have a chat about it?

**Comment by glogiotatidis** [comment]
Agree that commit messages can be more error prone. I like the `set-config` tool. Since you already moved with branching let's see how this works and we can re-eval in the future.

**Comment by jgmize** [comment]
This is set up so I'm closing this; further feedback & discussion in https://github.com/mozmar/www-config/issues/1
